name: test_email

on:
  workflow_dispatch:

jobs:
  send_mail:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Send  email
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{ secrets.MAIL_CONNECTION }} 
        subject: "Test from Omnivook"
        body: "via connection url Omnivook eBook."
        to: ${{ secrets.MAIL_TO }}
        from: ${{ secrets.MAIL_FROM }}